### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by Trother555** [KimiNewt/pyshark#275]
I got the following exception running sniff with timeout:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyshark\capture\capture.py", line 132, in load_packets
    try:
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyshark\capture\capture.py", line 247, in apply_on_packets
    coro = asyncio.wait_for(coro, timeout)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

I've checked capture.py and seen that it tries code that excepts TimeoutError and passes this exception:
 ```
try:
            self.apply_on_packets(keep_packet, timeout=timeout)
            self.loaded = True
except TimeoutError:
            pass
```

But the thing is that the code throws not TimeoutError, but concurrent.futures._base.TimeoutError. So I worked this problem around by adding this line to capture.py:

`from concurrent.futures._base import TimeoutError`

I'd like to know if this is a bug or I'm using it wrong or my python/platform is not supported?

I'm using

`Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32`

**Comment by KimiNewt** [comment]
It's a bug, fixed in master, will update distribution soon,

**Comment by ilanbiala** [comment]
I'm still seeing this issue, has this been released?

**Comment by LyleLaii** [comment]
I'm still seeing this issue，pyshark  0.4.1，has this been released?
