### ISSUE TITLE
Getting pyshark packets from queue / pickle problems

### ISSUE THREAD

**Issue by d6bels** [KimiNewt/pyshark#63]
Hello,

As I was trying to capture packets live using `pyshark` and do some multiprocessing, I encountered problems when getting a packet previously put in a `multiprocessing.Queue` or when I try to un-pickle it.  Here is the error I get:

> python2.7/site-packages/pyshark/packet/layer.py", line 48, in \__getattr__
> val = self.get_field_value(item, raw=self.raw_mode)
> (... multiple times ...)
> **RuntimeError**: maximum recursion depth exceeded while calling a Python object`.

This error comes whatever the `sys.recursionlimit` is set to (I stopped trying after raising it by a ten-factor).
I noted that this issue does not happen when using `Queue.Queue` so I suspect this is a problem with "reconstructing" the object when it's unpickled (as `multiprocessing.Queue` uses some kind of pickler, while `Queue.Queue` is a `collections.deque` under the hood).  

Is this a "normal" behavior and pyshark's packets cannot be pickled and un-pickled or is it a real issue ?

Here is the code I use to reproduce that issue
I am running a standard 2.7.9 python on RedHat 6.5

```python
import pyshark
import multiprocessing
import Queue
import cPickle as pickle

# Capture on eth0
interface = pyshark.LiveCapture(interface="eth0")

def queue_test(queue):
    """ Puts captured packets in a queue, then un-queue them and display """
    for packet in interface.sniff_continuously(packet_count=5):
        queue.put(packet)

    while not queue.empty():
        packet = queue.get()
        print "Packet {} {}".format(packet.highest_layer,packet._packet_string)


def pickle_test():
    """ Immediately pickle and unpickle the packet to display it"""
    for packet in interface.sniff_continuously(packet_count=5):
        pickled_packet = pickle.loads(pickle.dumps(packet, pickle.HIGHEST_PROTOCOL))
        print "Packet #{}, {} {}".format(pickled_packet.highest_layer,pickled_packet._packet_string)

if __name__ == "__main__":
    # Try two types of queues
    normal_queue = Queue.Queue()
    process_queue = multiprocessing.Queue()

    # Runs fine
    #queue_test(normal_queue)

    # Both crash with a RuntimeError
    queue_test(process_queue)
    #pickle_test()
```

For cross-references, I had a [question posted on StackOverflow about this problem](http://stackoverflow.com/questions/28746662/pyshark-packets-queue-and-pickle-errors), but I am logging this issue here because it didn't get much attention.

Thanks you

**Comment by KimiNewt** [comment]
This is caused by the fact that some of the classes packet uses override getattr. Fixed in 541fc525a5b600bfd6668765b2fe79ce8149aae0

**Comment by d6bels** [comment]
Thanks, the infinite loop probIem does not occur anymore, but the issue is still not completely solved.
I now have a problem unpickling packets because of :

>File "/home/kbleniat/Lab/spymoon/spypy/lib/python2.7/site-packages/pyshark-0.3.4-py2.7.egg/pyshark/packet/layer.py", line 86, in \__new__
>    print callable(getattr(main_field, "get_default_value"))
>AttributeError: 'str' object has no attribute 'get_default_value'

It seems that in `LayerFieldsContainer.__new__`, the parameter `main_field` is not always an object having the `get_default_value` method.

I was able to bypass the problem by checking that it has the method before calling it but it is not a fix in any way.

*packet/layer.py*
```python
def __new__(cls, main_field, *args, **kwargs):
    if hasattr(main_field, "get_default_value"):  # FIXME
        obj = str.__new__(cls, main_field.get_default_value(), *args, **kwargs)
    else:
        obj = str.__new__(cls, main_field, *args, **kwargs)
    obj.fields = [main_field]
    return obj
```

**Comment by he2ss** [comment]
Hello,

I have the same issue as @d6bels and i also patched it in my own code:

```
from pyshark.packet import layer
class LayerFieldsContainer(layer.LayerFieldsContainer):
    def __new__(cls, main_field, *args, **kwargs):
        if hasattr(main_field, 'get_default_value'):
            obj = str.__new__(cls, main_field.get_default_value(), *args, **kwargs)
        else:
            obj = str.__new__(cls, main_field, *args, **kwargs)
        obj.fields = [main_field]
        return obj
layer.LayerFieldsContainer = LayerFieldsContainer
```

**Comment by leonisawesome** [comment]
I am running into this new now myself.  

Latest Mac OS (10.13.6)
Latest Anaconda (4.5.11) with all patches installed
